---
galaxy_info:
  author: w0
  description: Install Traefik v3 as a hardened systemd service with declarative configuration.
  role_name: traefik
  namespace: w0

  license: Apache-2.0

  min_ansible_version: "2.10"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

  galaxy_tags:
    - traefik
    - reverseproxy
    - loadbalancer
    - proxy
    - web
    - http
    - https
    - systemd
    - service

dependencies: []
